update version number

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -32,15 +32,32 @@ jobs:
         restore-keys: |
           ${{ runner.os }}-pip-${{ matrix.python-version }}-
           ${{ runner.os }}-pip-
-    - name: Install dependencies
+    - name: Install Dependencies with Retry
       run: |
         cp packaging/setup.py .
-        pip install .
+        max_attempts=5
+        sleep_seconds=10
+        attempt_num=1
+        until timeout $sleep_seconds pip install . || [[ $attempt_num -eq $max_attempts ]]
+        do
+          echo "Attempt $attempt_num of $max_attempts failed! Trying again in $sleep_seconds seconds..."
+          sleep $sleep_seconds
+          ((attempt_num++))
+        done
+
+        if [[ $attempt_num -eq $max_attempts ]]; then
+          echo "All $max_attempts attempts have failed!"
+          exit 1
+        fi
+    - name: Install Test Dependencies
+      run: |
         python tests/smoke_test.py
         python -m pip install --upgrade pip
         pip install --no-deps -r tests/requirements.lock
         pip install .
     - name: Run Tests
+      env:
+        CI: true
       run: |
         python -m unittest discover tests -v
 
